ping:
  handler: ${self:custom.path.app}/handlers/utils/ping.handler
  description: Ping test
  timeout: 3
  reservedConcurrency: 1
  events:
    - http:
        path: utils/ping
        method: GET
        private: false
        cors: ${self:custom.http.cors}

pingAuth:
  handler: ${self:custom.path.app}/handlers/utils/ping.handler
  description: Ping test with authentication
  timeout: 3
  reservedConcurrency: 1
  events:
    - http:
        path: utils/ping/auth
        method: GET
        private: true
        cors: ${self:custom.http.cors}
