Resources:
  LambdaSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "${self:provider.stackName}-lambdaSecurityGroup"
      GroupDescription: "Allow all outbound traffic, no inbound"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 127.0.0.1/32
      VpcId:
        Ref: Vpc
